
INSERT INTO students (
    name, university, faculty, desired_industry, desired_role, graduation_year,
    email, phone, status, tags, staff_id, source_company, interview_reason
) VALUES
('Konishi Reina', '青山学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('オオイシ　サトシ', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', NULL),
('ひろかみ あらた', '成蹊大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('安岡 聖悟', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('安立勇希', '創価大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('伊藤　龍斗', '埼玉大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('伊藤　蓮', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('臼井 悠人', '学習院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('榎本 紗来', '専修大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('横山翔', '千葉大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('横倉 圭太', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('岡田真子', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('関谷　琉雅', '福島大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '企業分析'),
('岸本茉那人', '小樽商科大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('岩下和史', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('吉田 修透', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('宮嶋杏佳', '横浜市立大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('宮脇 智聖', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('許 嘉楠', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('金 将然', '明星大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('恒松 大喜', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('荒木　幸夫', '青山学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('高橋 優太', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('佐藤悠人', '青山学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('坂本修也', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('山本 依月', 'お茶の水大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('山﨑 裕剛', '岡山大学大学院', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('四辻 佑太', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('寺尾理志', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('柴谷 俊', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('秋山 太希', '中央大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('住吉　杏介', '茨城大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('小林　蒼生', '横浜国立大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', NULL),
('松本 力哉', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('松澤 弦武', '日本大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('城地 慶音', '青山学院大学大学院', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('森谷　楓', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', NULL),
('清水佑紀', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('石井　敦貴', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('石川 天斗', '中央大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('前田　陸斗', '関西学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('早見　壮平', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', NULL),
('村上　広大', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', NULL),
('村地悠記', '立命館大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('村田 新直', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('大部友暉', '電気通信大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('瀧澤　日翔', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('谷 淳平', '名古屋大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('竹永 隆貴', '大阪大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('中山 颯斗', '小樽商科大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('堤 咲菜', '京都女子大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('藤 雄介', '関西学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('南　景翔', '近畿大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('薄井里奈', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('八木　涼太', '九州大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('武川怜', '弘前大学大学院', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('北村洋輝', '白鷗大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('卜部龍悟', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('涌田 拓弥', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('廣瀬　愛果', '横浜市立大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('齋藤誠五郎', '慶応義塾大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('東海林優衣', '東北学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('内田健斗', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('小林裕心', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('木村樹生', '九州大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('村上 茉悠', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('添田 理奈', '津田塾大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('志水 奏太', '関西学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('大畑美優', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('成田 大地', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('白石桃香', '鶴見大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('野村 颯摩', '名古屋国際高価専門職大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('松田　駿', '青山学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('前田 陸斗', '関西学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('森田 大悟', '近畿大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('重信廣昌', '熊本大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('峰野雄大', '名古屋大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('竹内裕貴', '明治大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('小野莉愛', '神戸大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('近藤 彩実', '学習院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '企業分析'),
('亀山あぐり', '神戸市外国語大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('卜部龍悟', '同志社大学', '政策学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('石田 怜奈', '明治大学', '情報コミュニケーション学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('東海林優衣', '東北学院大学', '情報学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('原裕治', '都立大学', '経済経営学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('横山翔', '千葉大学', '法政経学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('吉田智尋', '法政大学', 'グローバル教育学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('佐藤 誓', '明治大学', '経営学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('辻 凌和', '同志社大学', 'スポーツ健康科学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('越後遥', '立命館大学', '経営学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('飯岡朋香', '東京理科大学', '理工学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('矢形優介', '北海道大学大学院', '工学院', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('清水桃花', '杏林大学', '総合政策学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('永田未優', '同志社女子大学', '現代社会学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('東雲 洸樹', '関西学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '企業分析'),
('田村康介', '早稲田大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('若林 にな', '成城大学', '経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('渡会愛梨', '東京薬科大学', '生命科学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('藤田大輝', '早稲田大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('古谷海斗', '大東文化大学', '経営学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('長谷聡士', '早稲田大学', 'スポーツ科学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('森田聖之助', '青山学院大学', '教育人間科学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('長澤　航汰', '早稲田大学大学院', '基幹理工学研究科 電子物理システム学専攻', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('横川心人', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '企業分析'),
('藤田彩菜', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('わたなへ　ゆうし', '富山大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('籠 裕亮', '東京工業大学大学院', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('奥山晴希', '静岡大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('安元麻尋', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('山田瑠里', '上智大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('田中まさと', '一橋大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('菅野　拓人', '東洋大学大学院', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('柳沼尚希', '横浜国立大学', '経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('村田 りく', '早稲田大学', '教育学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('貞森 幸輝', '東京工業大学大学院 修士課程1年目', '物質理工学院 材料系材料コース', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('安元麻尋', '早稲田大学', '政治経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('矢野藍人', '成蹊大学', '文学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('小澤 翼', '東京理科大学', '工学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('三原　愛咲', '早稲田大学', '文化構想学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('宮本恵輔', '同志社大学', '経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('山口誠', '学習院大学', '文学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('大﨑一輝', '神戸大学大学院 修士課程1年目', '工学研究科 建築学専攻', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('加藤悠大', '立命館大学', '国際関係学部 国際関係学科', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('石黒 大晴', '青山学院大学', '文学部 英米文学科', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('大野結菜', '早稲田大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '企業分析'),
('長谷川侑香', '法政大学', 'キャリアデザイン学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('竹内裕貴', '明治大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('大久保 礼', '東京理科大学', '理工学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('吉田陽菜', '関西学院大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('荒井将人', '慶応義塾大学', '総合政策学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('飯田小夏', '関西学院大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('米重紗良', '慶應義塾大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('本田 雄太', '立命館大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('西森新之助', '法政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('石黒 大晴', '青山学院大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('山河 楽々', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('小澤輝哉', '東京薬科大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('齋藤秀樹', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('浅羽洵佑', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('鈴木康大', '順天堂大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('西村 若葉', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('大畑美優', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('中村 大樹', '立命館大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('宮崎 陸', '同志社大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('穴山　陽大', '中央大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '就活相談'),
('河野 徹平', '東洋大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('福井進之介', '明治大学', '経営学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('野村陸', '中央大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('小山', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '就活相談'),
('飯塚 彩夏', '東京家政大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('町田 優綾', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('増田悠斗', '東京大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('小幡恩', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('堀七寧', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('三宅啓太', '関西大学', '総合情報学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('中村沙耶', '立教大学', '経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('松平健太', '法政大学', '文学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('小河原洸希', '筑波大学', '人間学群 障害科学類', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('平田愛翔', '早稲田大学', '商学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('森元海翔', '早稲田大学', '人間科学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('杉山未来', '明治学院大学', '法学部 消費情報環境法学科', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('吉住 聖香', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('久保敬太', '関西大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('石井秀平', '駒澤大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '企業分析'),
('奥田大晴', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, '日本生命', '企業分析'),
('森 一希', '長崎大学修士課程1年目', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('山本真大', '日本大学', '経済学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('松本萌奈', '関西学院大学', '教育学部', NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'オービック', '就活相談'),
('稲葉俊太', '早稲田大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'KDDi', '企業分析'),
('角野 萌音', '立教大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談'),
('村井 向晴', '北翔大学', NULL, NULL, NULL, NULL, NULL, NULL, '面談', NULL, 1, 'マネフォ', '就活相談');
